### Root
GET http://127.0.0.1:7860

### Logs
GET http://127.0.0.1:7860?logs=container

### API
GET http://127.0.0.1:7860/api?query=What is Bureau Integration Service

### HuggingFace Root
GET https://huggingface.co/spaces/rahgadda/google-genai-local-server/

### HuggingFace Logs
GET https://huggingface.co/spaces/rahgadda/google-genai-local-server?logs=container

### HuggingFace Api
GET https://huggingface.co/spaces/rahgadda/google-genai-local-server?query=What is Bureau Integration Service
