
POST http://127.0.0.1:7860/api/chatwithum
Content-Type: application/json

{
    "query": "What is Bureau Integration Service "
}

###
GET https://huggingface.co/spaces/rahgadda/google-genai-local-server/api?query=What is Bureau Integration Service